services:
    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: crmpaketur
            MYSQL_DATABASE: crmpaketur
            MYSQL_PASSWORD: password
            TZ: 'Asia/Jakarta'
        ports:
            - 3306:3306
        volumes:
            - mysql-data:/var/lib/mysql

volumes:
    mysql-data: {}
